GRANT ALL ON public.walk_pickup_codes TO service_role;
GRANT ALL ON public.petwalker_profiles TO service_role;
GRANT ALL ON public.pets TO service_role;
GRANT ALL ON public.walk_sessions TO service_role;
GRANT ALL ON public.profiles TO service_role;
GRANT ALL ON public.user_roles TO service_role;
GRANT ALL ON public.walker_tracking TO service_role;
GRANT ALL ON public.walk_offers TO service_role;
GRANT ALL ON public.petwalker_earnings TO service_role;
